apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py-github-art-10dec 
  janus-idp.io/tekton: py-github-art-10dec
  backstage.io/kubernetes-id: py-github-art-10dec
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-github-art-10dec
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  