apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-github-art-10dec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-github-art-10dec 
  name: py-github-art-10dec
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-github-art-10dec 
